version: '3.8'
services:
  alma8:
    image: perfsonar/unibuild-alma8:latest
    build:
        context: ../
        dockerfile: ./docker-envs/Dockerfile-alma8
    volumes:
      -  .:/app
  debian10:
    image: perfsonar/unibuild-debian10:latest
    build:
        context: ../
        dockerfile: ./docker-envs/Dockerfile-debian10
    volumes:
      -  .:/app
