version: '3.9'

###
# Some repeated defaults:
###
x-volumes:
  &default-volumes
  - .:/app

###
# Services
###
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el7
      network: host
    network_mode: "host"
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el8
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el9
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10@sha256:
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10@sha256:
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10@sha256:
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10@sha256:
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18@sha256:
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18@sha256:
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18@sha256:
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18@sha256:
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20@sha256:
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20@sha256:
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20@sha256:
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20@sha256:
    volumes: *default-volumes
