version: '3.9'

###
# Some repeated defaults:
###
x-volumes:
  &default-volumes
  - .:/app

###
# Services
###
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el7
      network: host
    network_mode: "host"
    volumes: *default-volumes
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el8
    volumes: *default-volumes
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el9
    volumes: *default-volumes
  d10_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/d10:multiarch@sha256:6e15c6700ba7f6d4f56bbaf0e5034ee872bcbc2ab91ab8b5630f6f18a812f618
    volumes: *default-volumes
  d10_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/d10:multiarch@sha256:cbbd4d617ea55062b891bf5160fe01047e1bbf0c84d0f8fddf3eb8f4698a9b13
    volumes: *default-volumes
  d10_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/d10:multiarch@sha256:2d67964a34ba8f6250cff4d833a70fa5644a1503d893965e42b1c43355e84ed7
    volumes: *default-volumes
  d10_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/d10:multiarch@sha256:72dea5b899956112720c31c5502cc43cd97dc44e41346040c477586adf3da3f3
    volumes: *default-volumes
  u18_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u18:multiarch@sha256:51826928c84fdee51484af8a6551f991a747ba05337015d392350c25c670519b
    volumes: *default-volumes
  u18_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u18:multiarch@sha256:774688a068e814883c48136742c377f2b0eb296c60d9ef743f918b8084658eb2
    volumes: *default-volumes
  u18_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u18:multiarch@sha256:7e0097b3b993f97ddb40f6d6d001bd9b8ab9be829f815b4e6bef6337eb6cdd02
    volumes: *default-volumes
  u18_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u18:multiarch@sha256:72e37524c58e8ef717d6fc5e318547910bc1565e0bc19cf630dc0e6a3b9ec30f
    volumes: *default-volumes
  u20_amd64:
    platform: "linux/amd64"
    image: ghcr.io/perfsonar/unibuild/u20:multiarch@sha256:92e43427d5b4dd35bcabbc8194697cea90370bf1cd79186b0eec9071d1393120
    volumes: *default-volumes
  u20_arm64:
    platform: "linux/arm64"
    image: ghcr.io/perfsonar/unibuild/u20:multiarch@sha256:a4f6d97f39349f4579a9a66dd33c7091f3737cf3fdf703b01fb33909d93eca92
    volumes: *default-volumes
  u20_armv7:
    platform: "linux/arm/v7"
    image: ghcr.io/perfsonar/unibuild/u20:multiarch@sha256:1acc2885d7630cc94e90ee6e59afaf424212c3d21b077e853d06b5671bcd9c11
    volumes: *default-volumes
  u20_ppc64le:
    platform: "linux/ppc64le"
    image: ghcr.io/perfsonar/unibuild/u20:multiarch@sha256:20f6628f69ca1fab6a945f6e41dc9cf19edd5450b70033b7bc2eef5838d18db6
    volumes: *default-volumes
