version: '3.8'
services:
  el7:
    image: ghcr.io/perfsonar/unibuild/el7:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el7
      network: host
    network_mode: "host"
    volumes:
      - .:/app
  el8:
    image: ghcr.io/perfsonar/unibuild/el8:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el8
    volumes:
      -  .:/app
  el9:
    image: ghcr.io/perfsonar/unibuild/el9:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-el9
    volumes:
      -  .:/app
  d10:
    image: ghcr.io/perfsonar/unibuild/d10:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-d10
    volumes:
      -  .:/app
  u18:
    image: ghcr.io/perfsonar/unibuild/u18:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-u18
    volumes:
      -  .:/app
  u20:
    image: ghcr.io/perfsonar/unibuild/u20:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-u20
    volumes:
      -  .:/app
  u22:
    image: ghcr.io/perfsonar/unibuild/u22:latest
    build:
      context: ../
      dockerfile: ./docker-envs/Dockerfile-u22
    volumes:
      -  .:/app
